# 1. API Version and Type
apiVersion: v1
kind: Service            # Defines this resource as a Service (Networking)
metadata:
  name: my-health-check-api-service # The name used to identify the service
spec:
  # 2. Service Type
  # NodePort makes the service accessible outside the cluster via your machine's IP
  type: NodePort         

  # 3. The Selector (The "Bridge")
  selector:
    # This MUST match the 'app' label used in your deployment.yml
    app: my-health-check-api 

  # 4. Port Configuration
  ports:
    - protocol: TCP
      port: 80           # The port other services inside the cluster use to talk to this one
      targetPort: 3000   # The actual port your Node.js app is listening on inside the container
